#!/usr/bin/env bash
# Idempotent setup for vendor/primus-core. Runs from this repository's
# postinstall hook, so a fresh `git clone && pnpm install` produces a
# ready-to-build state without any manual ceremony.
#
# What it does:
# 1. Initialise the primus-core submodule (shallow).
# 2. Drop a local .npmrc into vendor/primus-core so pnpm install
#    behaves like yarn (hoisted node_modules, time-based resolution).
# 3. Hide that .npmrc plus build artefacts from the submodule's
#    git status by appending to its info/exclude.
#
# This script does NOT install vendor deps or build vendor bundles.
# That is `pnpm build:vendor`.

set -euo pipefail

# Resolve repo root (script lives in <repo>/scripts/).
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# `.git` is a directory in a normal clone but a *file* in a linked worktree (and
# in a submodule checkout), so testing for a directory here wrongly skipped the
# whole setup inside worktrees. Ask git instead.
if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "[setup-vendor] not a git repo — skipping" >&2
  exit 0
fi

# 1. submodule init (idempotent; cheap when already initialised).
if [ ! -f vendor/primus-core/package.json ]; then
  echo "[setup-vendor] initialising vendor/primus-core submodule (shallow)..."
  git submodule update --init --depth 1 vendor/primus-core
fi

# 2. drop pnpm config that makes the fork build cleanly with pnpm.
NPMRC="vendor/primus-core/.npmrc"
cat > "$NPMRC" <<'NPMRC_EOF'
# Generated by scripts/setup-vendor-config.sh — do not commit upstream.
# Makes pnpm install behave like yarn 1 for this fork:
#   - hoisted node_modules (so webpack picks up phantom transitive deps)
#   - time-based version resolution (avoids picking newer minors than
#     yarn.lock had, which broke antd vs @types/react in upstream)
node-linker=hoisted
shamefully-hoist=true
auto-install-peers=true
strict-peer-dependencies=false
resolution-mode=time-based
NPMRC_EOF

# 3. exclude build products from submodule git status.
#
# pnpm-lock.yaml is deliberately NOT excluded: it is the fork's authoritative
# dependency lock and any change must remain visible in submodule status.
# Ask the submodule for its own gitdir rather than reconstructing the path:
# where git stores it varies between a normal clone and a linked worktree.
#
# The `.git` guard matters: rev-parse walks up, so on a vendored (non-submodule)
# copy of the fork it would hand back the *superproject's* gitdir and we would
# append these lines to the wrong info/exclude.
if [ ! -e vendor/primus-core/.git ]; then
  echo "[setup-vendor] vendor/primus-core is not a git checkout — skipping exclude setup" >&2
  echo "[setup-vendor] ok — vendor/primus-core configured for pnpm"
  exit 0
fi

SUB_GIT_DIR="$(git -C vendor/primus-core rev-parse --absolute-git-dir)"
EXCLUDE_FILE="$SUB_GIT_DIR/info/exclude"
mkdir -p "$(dirname "$EXCLUDE_FILE")"
touch "$EXCLUDE_FILE"
for line in ".npmrc" "node_modules/" "build/"; do
  grep -qxF "$line" "$EXCLUDE_FILE" || echo "$line" >> "$EXCLUDE_FILE"
done

echo "[setup-vendor] ok — vendor/primus-core configured for pnpm"
